apiVersion: v1
kind: Pod
metadata:
  name: vault-cli
  namespace: platform
spec:
  containers:
  - name: cli
    image: hashicorp/vault:1.17.0
    command: ["sh"]
    stdin: true
    tty: true
    volumeMounts:
    - name: vault-ca
      mountPath: /vault/ca
      readOnly: true
  volumes:
  - name: vault-ca
    secret:
      secretName: vault-internal-ca

