apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault
  namespace: apps
  annotations:
    kubernetes.io/ingress.class: traefik
    # USE HTTPS to the Service (Vault now serves only HTTPS)
    traefik.ingress.kubernetes.io/service.serversscheme: https
    # USE the ServersTransport we created (with the CA)
    traefik.ingress.kubernetes.io/service.serverstransport: ingress-traefik-vault-tls@kubernetescrd
spec:
  rules:
    - host: development.vault.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hashicorp-vault
                port:
                  number: 8200
