apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vault-auth-global.yaml

configMapGenerator:
  - name: vso-values
    namespace: platform
    files:
      - values.yaml=values.yaml

generatorOptions:
  disableNameSuffixHash: true