apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole-deployment
spec:
  replicas: 1
  template:
    spec:
      nodeSelector:
        cfke.io/provider: hetzner
        cfke.io/subregion: central
      containers:
        - name: pihole
          env:
            - name: FTLCONF_webserver_api_password
              valueFrom:
                secretKeyRef:
                  name: htz-pihole-webpassword
                  key: password
