apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - np-tailscale-to-adguard.yaml
  - ingress.yaml
  - service.yaml
  - deployment.yaml
  - pvc.yaml
  - dns-service.yaml
  - namespace.yaml