apiVersion: secrets.hashicorp.com/v1beta1
metadata:
  name: grafana-secret-sync
  namespace: observability
spec:
  vaultAuthRef: vault-auth   # points to the VaultAuth in platform
  mount: k8s
  path: k8s/observability/grafana
  type: kv-v2
  refreshAfter: 5m
  destination:
    name: grafana
    create: true
    overwrite: true
