apiVersion: v1
kind: ConfigMap
metadata:
  name: adguard-config
  namespace: dns
data:
  AdGuardHome.yaml: |
    bind_host: "0.0.0.0"

    dns:
      bind_hosts:
        - "0.0.0.0"
      port: 53
      bootstrap_dns:
        - "1.1.1.1:53"
        - "8.8.8.8:53"
      upstream_dns:
        - "1.1.1.1"
        - "8.8.8.8"
      blocked_response: "0.0.0.0"

    filtering:
      enabled: true
      filters:
        - "https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt"
        - "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"
    
    logging:
      level: info
