apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole-ui
  namespace: pihole
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
    - pihole
  defaultBackend:
    service:
      name: pihole-service
      port:
        number: 80
